<?php if($this->isAccessable) { ?>
    <div class="meliscmsnews-dashboard-workflow">
        <!-- two main tab (demands & answers) -->
        <div class="dashboard-workflow-container-news">
            <ul class="nav-tabs clearfix">
                <li class="active">
                    <a data-toggle="tab" href="#dashboard-workflow-demand<?php echo $this->pluginId ?>">
                        <i class="fa fa-users"></i><span class="a-text"><?= $this->translate('tr_meliscmsnews_dashboard_workflow_Users demands'); ?></span>
                    </a>
                </li>
                <li>
                    <a data-toggle="tab" href="#dashboard-workflow-answer<?php echo $this->pluginId ?>">
                        <i class="fa fa-user"></i><span class="a-text"><?= $this->translate('tr_meliscmsnews_dashboard_workflow_My demands'); ?></span>
                    </a>
                </li>
            </ul>
        </div>

        <div class="tab-content">
            <!-- DEMAND TAB -->
            <div id="dashboard-workflow-demand<?php echo $this->pluginId ?>" class="dashboard-workflow-tabs-news tab-pane widget widget-tabs widget-tabs-icons-only-2 widget-activity margin-none border-none active">
          
                <!-- Tabs Content -->
                <div class="widget-body padding-none dashboard-widget-workflow">
                    <div class="tab-content">
                        <?php
                        if (!empty($this->tabItemsDemandsForMe)) {
                            $isFirstEntry = true;
                            foreach ($this->tabItemsDemandsForMe as $keyTab => $valueTab) {
                                ?>
                                <div class="tab-pane <?php echo ($isFirstEntry) ? 'active' : '';  $isFirstEntry = false; ?>" id="<?php echo $this->pluginId . '_' . $keyTab; ?>">
                                    <ul class="list">
                                        <?php
                                            foreach ($valueTab as $key => $wf) {
                                            ?>
                                            <li>
                                                <div class="wd-cont clearfix"
                                                     data-wf-id="<?= $wf[0]['cnews_wf_item_key_id']; ?>"
                                                     data-wf-type="<?= $wf[0]['cnews_wf_type']; ?>"
                                                     data-wf-details="<?= $wf[0]['cnews_wf_details']; ?>"
                                                     data-wf-opening-js="<?= $wf[0]['cnews_wf_opening_js']; ?>" >

                                                     <span class="fa fa-arrow-down"></span>

                                                     <div class="d-workflow-action-cont">
                                                         <?php
                                                            if (count($wf) == 1 && (!(int) $wf[0]['cnews_wf_process_finished']))
                                                            {
                                                         ?>
                                                            <span class="wd-validate" data-wfe-id="<?php echo $wf[0]['cnews_wfe_id'] ;?>" data-wfe-wf-id="<?php echo $wf[0]['cnews_wfe_wf_id'] ;?>"><i
                                                                    class="fa fa-check fa-color-green"
                                                                    title="<?= $this->translate('tr_meliscmsnews_workflow_validate'); ?>"></i></span>
                                                            <span class="wd-refuse" data-wfe-id="<?php echo $wf[0]['cnews_wfe_id'] ;?>" data-wfe-wf-id="<?php echo $wf[0]['cnews_wfe_wf_id'] ;?>"><i
                                                                    class="fa fa-times fa-color-red"
                                                                    title="<?= $this->translate('tr_meliscmsnews_workflow_refuse'); ?>"></i></span>
                                                         <?php
                                                            }
                                                            else
                                                            {
                                                                if (!empty($wf[1]))
                                                                {
                                                                    $textAction = $this->translate('tr_meliscmsnews_workflow_' . $wf[1]['cnews_wfe_action']);
                                                                    if ($wf[1]['cnews_wfe_action'] == 'VALIDATED')
                                                                        $actionColor = 'validate';
                                                                    else
                                                                        if ($wf[1]['cnews_wfe_action'] == 'REFUSED')
                                                                            $actionColor = 'refuse';
                                                                    ?>
                                                                    <span class="wd-action-<?= $actionColor; ?>" onclick="preventClick(event);"><?= $textAction; ?></span>
                                                                    <?php
                                                                }
                                                            }
                                                         ?>
                                                         <span class="wd-see"><i class="fa fa-eye" onClick="<?= $wf[0]['cnews_wf_opening_js']; ?>"></i></span>
                                                    </div>

                                                    <div class="wd-cont-head">
                                                        <span class="wd-info-cont wd-date"><?= $wf[0]['cnews_wfe_date']; ?></span> -
                                                        <span class="wd-info-cont"><?= $wf[0]['cnews_wf_details']; ?></span>
                                                    </div>
                                                    <div class="wd-cont-content">
                                                        <?php
                                                            $demand = $wf[0];
                                                            $answer = null;
                                                            if (!empty($wf[1]))
                                                                $answer = $wf[1];

                                                            $actionColor = '';
                                                            if (!empty($answer))
                                                            {
                                                                if ($answer['cnews_wfe_action'] == 'VALIDATED')
                                                                    $actionColor = 'validate';
                                                                else
                                                                    if ($answer['cnews_wfe_action'] == 'REFUSED')
                                                                        $actionColor = 'refuse';
                                                            }

                                                            $roleMore = '';
                                                            if (!empty($demand['cnews_wfe_to_role_name']))
                                                                $roleMore = ' / ' . $demand['cnews_wfe_to_role_name'];

                                                            $textActionDemand = $this->translate('tr_meliscmsnews_workflow_' . $demand['cnews_wfe_action']);
                                                            if($textActionDemand == 'Refused') {
                                                                $actionColor = 'refuse';
                                                            }

                                                            $textActionAnswer = '';
                                                            if (!empty($answer))
                                                                $textActionAnswer = $this->translate('tr_meliscmsnews_workflow_' . $answer['cnews_wfe_action']);
                                                        ?>
                                                        <p>
                                                                    <span class="wd-info-cont">
                                                                        <span class="wd-action-demand"><?= $textActionDemand; ?></span> <span><?= $demand['cnews_wfe_date']; ?> - <?= $this->translate('tr_meliscmsnews_workflow_user_from'); ?> <?= $demand['cnews_wfe_from_user_name']; ?>
                                                                            - <?= $this->translate('tr_meliscmsnews_workflow_user_to'); ?> <?= $demand['cnews_wfe_to_user_name'] . $roleMore; ?></span>
                                                                    </span>
                                                        </p>
                                                        <?php
                                                            if (!empty($answer))
                                                            {
                                                        ?>
                                                                <p>
                                                                    <span class="wd-info-cont">
                                                                        <span
                                                                            class="wd-action-<?= $actionColor; ?>"><?= $textActionAnswer; ?></span> <span><?= $answer['cnews_wfe_date']; ?>
                                                                            - <?= $this->translate('tr_meliscmsnews_workflow_user_from'); ?> <?= $answer['cnews_wfe_from_user_name']; ?>
                                                                            - <?= $this->translate('tr_meliscmsnews_workflow_user_to'); ?> <?= $answer['cnews_wfe_to_user_name']; ?></span>
                                                                    </span>
                                                                </p>
                                                        <?php
                                                            }
                                                        ?>
                                                    </div>
                                                </div>
                                            </li>
                                            <?php
                                        }
                                        ?>
                                    </ul>
                                </div>
                                <?php
                                }
                            }
                        ?>
                    </div>
                </div>

            </div>

            <!-- MY DEMANDS TAB -->
            <div id="dashboard-workflow-answer<?php echo $this->pluginId ?>" class="dashboard-workflow-tabs-news tab-pane widget widget-tabs widget-tabs-icons-only-2 widget-activity margin-none border-none">
                <!-- Tabs Content -->
                <div class="widget-body padding-none dashboard-widget-workflow">
                    <div class="tab-content">
                        <?php
                            if (!empty($this->tabItemsDemandsToOthers)) {
                                $isFirstEntry = true;
                                foreach ($this->tabItemsDemandsToOthers as $keyTab => $valueTab) {
                                    ?>
                                    <div class="tab-pane <?php echo ($isFirstEntry) ? 'active' : '';  $isFirstEntry = false; ?>" id="<?php echo $this->pluginId . '_' . $keyTab; ?>">
                                        <ul class="list">
                                            <?php
                                                foreach ($valueTab as $wf) {
                                                    ?>
                                                    <li>
                                                        <div class="wd-cont clearfix"
                                                             data-wf-id="<?= $wf[0]['cnews_wf_item_key_id']; ?>"
                                                             data-wf-type="<?= $wf[0]['cnews_wf_type']; ?>"
                                                             data-wf-details="<?= $wf[0]['cnews_wf_details']; ?>"
                                                             data-wf-opening-js="<?= $wf[0]['cnews_wf_opening_js']; ?>" >

                                                             <span class="fa fa-arrow-down"></span>

                                                             <div class="d-workflow-action-cont">
                                                                 <?php
                                                                     if (!empty($wf[1])) {
                                                                         $textAction = $this->translate('tr_meliscmsnews_workflow_' . $wf[1]['cnews_wfe_action']);
                                                                         if ($wf[1]['cnews_wfe_action'] == 'VALIDATED')
                                                                             $actionColor = 'validate';
                                                                         else
                                                                             if ($wf[1]['cnews_wfe_action'] == 'REFUSED')
                                                                                 $actionColor = 'refuse';
                                                                         ?>
                                                                         <span class="wd-action-<?= $actionColor; ?>" onclick="preventClick(event);"><?= $textAction; ?></span>
                                                                         <?php
                                                                     }
                                                                ?>
                                                                 <span class="wd-see"><i class="fa fa-eye" onClick="<?= $wf[0]['cnews_wf_opening_js']; ?>"></i></span>
                                                        <?php	/* 	<span class="wd-validate"><i class="fa fa-check fa-color-green" title="validate demand"></i></span>
                                                                <span class="wd-refuse"><i class="fa fa-times fa-color-red" title="refuse demand"></i></span> */ ?>
                                                             </div>

                                                            <div class="wd-cont-head">
                                                                <span class="wd-info-cont wd-date"><?= $wf[0]['cnews_wfe_date']; ?></span> -
                                                                <span class="wd-info-cont"><?= $wf[0]['cnews_wf_details']; ?></span>
                                                            </div>
                                                            <div class="wd-cont-content">
                                                                <?php
                                                                    $demand = $wf[0];
                                                                    $answer = null;
                                                                    if (!empty($wf[1]))
                                                                        $answer = $wf[1];

                                                                    $actionColor = '';
                                                                    if ($answer && $answer['cnews_wfe_action'] == 'VALIDATED')
                                                                        $actionColor = 'validate';
                                                                    else
                                                                        if ($answer && $answer['cnews_wfe_action'] == 'REFUSED')
                                                                            $actionColor = 'refuse';

                                                                    $roleMore = '';
                                                                    if (!empty($demand['cnews_wfe_to_role_name']))
                                                                        $roleMore = ' / ' . $demand['cnews_wfe_to_role_name'];

                                                                    $textActionDemand = $this->translate('tr_meliscmsnews_workflow_' . $demand['cnews_wfe_action']);
                                                                    $textActionAnswer = '';
                                                                    if (!empty($answer))
                                                                        $textActionAnswer = $this->translate('tr_meliscmsnews_workflow_' . $answer['cnews_wfe_action']);
                                                                ?>
                                                                <p>
                                                                    <span class="wd-info-cont">
                                                                        <span class="wd-action-demand"><?= $textActionDemand; ?></span> <span><?= $demand['cnews_wfe_date']; ?> - <?= $this->translate('tr_meliscmsnews_workflow_user_from'); ?> <?= $demand['cnews_wfe_from_user_name']; ?>
                                                                        - <?= $this->translate('tr_meliscmsnews_workflow_user_to'); ?> <?= $demand['cnews_wfe_to_user_name'] . $roleMore; ?></span>
                                                                    </span>
                                                                </p>
                                                                <?php
                                                                if (!empty($answer))
                                                                {
                                                                ?>
                                                                <p>
                                                                    <span class="wd-info-cont">
                                                                        <span class="wd-action-<?= $actionColor; ?>"><?= $textActionAnswer; ?></span> <span><?= $answer['cnews_wfe_date']; ?> - <?= $this->translate('tr_meliscmsnews_workflow_user_from'); ?> <?= $answer['cnews_wfe_from_user_name']; ?>
                                                                        - <?= $this->translate('tr_meliscmsnews_workflow_user_to'); ?> <?= $answer['cnews_wfe_to_user_name']; ?></span>
                                                                    </span>
                                                                </p>
                                                                <?php
                                                                }
                                                                ?>
                                                            </div>
                                                        </div>
                                                    </li>
                                                    <?php
                                                }
                                            ?>
                                        </ul>
                                    </div>
                                    <?php
                                }
                            }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        //this prevents confirmation request popin in wd-action-validate/wd-action-refuse class
        function preventClick(event){
            event.stopPropagation(); //
        }
    </script>
<?php } else { ?>
    <div class="no-rights-container">
        <span><?= $this->translate('tr_melisdashboardplugin_plugin_no_rights'); ?></span>
    </div>
<?php } ?>
