<div role="main" class="main">

	<section class="page-top">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<ul class="breadcrumb">
						<li><a href="index.html">Home</a></li>
						<li class="active">Pages</li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<h2>404 - Page Not Found</h2>
				</div>
			</div>
		</div>
	</section>

	<div class="container">
		<section class="page-not-found">
			<div class="row">
				<div class="col-md-6 col-md-offset-1">
					<div class="page-not-found-main">
						<h2>404 <i class="icon icon-file"></i></h2>
						<p>We're sorry, but the page you were looking for doesn't exist.</p>
					</div>
				</div>
				<div class="col-md-4">
					<h4>Here are some useful links</h4>
					<ul class="nav nav-list primary">
						<li><a href="/">Home</a></li>
						<li><a href="/features/id/7">Features</a></li>
						<li><a href="/customers/id/8">Customers</a></li>
						<li><a href="/id/1">Resources</a></li>
						<li><a href="/support/id/10">Support</a></li>
						<li><a href="/id/1">Partners</a></li>
						<li><a href="/community/id/14">Community</a></li>
					</ul>
				</div>
			</div>
		</section>
	</div>
	
</div>