<?php
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->newsId . '_' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
?>

<div <?php echo $id; ?> data-melisKey='<?php echo $data_melisKey; ?>' class="innerAll col-md-8">
	<div class="widget-head widget-red">
		<h3 class="heading"><i class="icon-stocks-up fa fa-fw"></i> <?php echo $this->translate('tr_meliscmsnews_pagecomment_add_comments'); ?></h3>
	</div>
	<div class="widget-body">
    	<?php
        	$form = $this->commentForm;
        	$form->get('pcom_text')->setAttribute('id',$this->newsId.'_id_pcom_text');
        	$form->prepare();
        	echo $this->form()->openTag($form); 
        	echo $this->melisFieldCollection($form);
    	?>
    	<button type="button" class="btn btn-success float-right btnAddNewsComment" data-newsid="<?php echo $this->newsId?>"  disabled><i class="fa fa-comment"></i> <?php echo $this->translate('tr_meliscmsnews_comments_add'); ?></button>
    	<?php
        	echo $this->form()->closeTag(); 
        ?>
	</div>
</div>
<script type="text/javascript">
    $(function() {
    	var selector = "textarea[id='<?php echo $this->newsId.'_id_pcom_text'; ?>']";

			melisTinyMCE.createTinyMCE("tool", selector, {
				height: 250, 
				setup: function (editor) {
					editor.on('keyup blur', function () {		            	
						if (editor.getContent() != '') {
							$(selector).closest('form').find('.btnAddNewsComment').removeAttr('disabled');
						} else {
							$(selector).closest('form').find('.btnAddNewsComment').attr("disabled", "disabled");
						}	

						editor.save();	                	                
					});
				},
			});
    });
</script>