<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' . $this->newsId . '_' . $this->zoneconfig['conf']['id'] . '"';
$data_melisKey = $this->melisKey;
$now = '<span class="date box-generic">'.$this->translate('tr_meliscmsnews_pagecomment_today').'</span>';
$previousComments = '<span class="date box-generic"><strong>%s</strong>%s</span><div class="separator"><span class="type glyphicons comments">%s <i></i></span></div>';
$oldDate = '';

foreach ($this->comments as $comment)
    $matchDate[] = $comment['month'] . ' ' . $comment['day'];

?>
<div <?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' class="innerAll">
    <ul class="timeline">
        <?php foreach($this->comments as $comment):
            if ($comment['isToday']):

                $name = !empty($comment['name'])? $comment['name'] : $this->translate('tr_meliscmsnews_page_tab_comments_no_user');
                $email = !empty($comment['email'])? $comment['email'] : $this->translate('tr_meliscmsnews_page_tab_comments_no_user');
                ?>
                <li class="active">
                    <div class="separator bottom">
                        <?= $now; ?>
                        <span class="type glyphicons comments"><?= $this->translate($comment['type']); ?> <i></i></span>
                    </div>
                    <div class="widget widget-heading-simple widget-body-white margin-none pagecomment">
                        <div class="widget-body">
                            <div class="media">
                                <div class="media-object float-left"><img src="<?= $comment['thumbnail']; ?>" width="50" alt="Image" class="rounded-circle"/></div>
                                <div class="media-body">
                                    <span class="text-danger"><i class="fa fa-user"></i> <?= $this->escapeHtml($name); ?></span><br/>
                                    <span class="muted"><i class="fa fa-envelope"></i> <?= $this->escapeHtml($email) ?></span>
                                    <span class="muted text-small clearfix"><i class="fa fa-clock-o"></i> <?= $comment['time']; ?></span>
                                </div>
                            </div>
                            <div class="clearfix">
                                <h4>
                                    <?php
                                        $type = $this->translate($comment['type']);
                                        if ($type !== 'WF') {
                                            echo $this->escapeHtml($comment['cnews_com_title']);
                                        } else {
                                            echo ($comment['cnews_com_title']);
                                        }
                                    ?>
                                </h4>
                            </div>
                            <div class="alert alert-gray">
                                <?php
                                $type = $this->translate($comment['type']);
                                if ($type == 'WF') {
                                    echo $this->escapeHtml($comment['cnews_com_text']);
                                } else {
                                    echo ($comment['cnews_com_text']);
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                </li>
                <?php $now = ''; endif; endforeach; ?>
        <?php

        $lastItemMonth = null;
        $lastItemDay   = null;
        $isDateDisplayed = true;

        foreach ($this->comments as $comment):
            if (!$comment['isToday']):
                ?>
                <?php
                if (($lastItemMonth === $comment['month']) && ($lastItemDay === $comment['day'])) {
                    $name = !empty($comment['name'])? $comment['name'] : $this->translate('tr_meliscmsnews_page_tab_comments_no_user');
                    $email = !empty($comment['email'])? $comment['email'] : $this->translate('tr_meliscmsnews_page_tab_comments_no_user');
                    ?>
                    <li class="active">
                        <div class="separator bottom">
                            <?php if ($isDateDisplayed): ?>
                                <?= sprintf($previousComments, $comment['day'], $comment['month'], $this->translate($comment['type'])) ?>
                            <?php endif; ?>
                            <span class="type glyphicons comments"><?= $this->translate($comment['type']); ?> <i></i></span>
                        </div>

                        <div class="widget widget-heading-simple widget-body-white margin-none pagecomment">
                            <div class="widget-body">
                                <div class="media">
                                    <div class="media-object float-left"><img src="<?= $comment['thumbnail']; ?>" width="50" alt="Image" class="rounded-circle"/></div>
                                    <div class="media-body">
                                        <span class="text-danger"><i class="fa fa-user"></i> <?= $this->escapeHtml($name); ?></span><br/>
                                        <span class="muted"><i class="fa fa-envelope"></i> <?= $this->escapeHtml($email); ?></span>
                                        <span class="muted text-small clearfix"><i class="fa fa-clock-o"></i> <?= $comment['time']; ?></span>
                                    </div>
                                </div>
                                <div class="clearfix">
                                    <h4>
                                        <?php
                                        $type = $this->translate($comment['type']);
                                        if ($type !== 'WF') {
                                            echo $this->escapeHtml($comment['cnews_com_title']);
                                        } else {
                                            echo ($comment['cnews_com_title']);
                                        }
                                        ?>
                                    </h4>
                                </div>
                                <div class="alert alert-gray">
                                    <?php
                                    $type = $this->translate($comment['type']);
                                    if ($type == 'WF') {
                                        echo $this->escapeHtml($comment['cnews_com_text']);
                                    } else {
                                        echo ($comment['cnews_com_text']);
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                    </li>
                    <?php $isDateDisplayed = false;
                } else {  $isDateDisplayed = true;
                    $name = !empty($comment['name']) ? $comment['name'] : $this->translate('tr_meliscmsnews_page_tab_comments_no_user');
                    $email = !empty($comment['email']) ? $comment['email'] : $this->translate('tr_meliscmsnews_page_tab_comments_no_user');
                    ?>
                    <li class="active">

                        <div class="separator bottom">
                            <?php if ($isDateDisplayed): ?>
                                <?= sprintf($previousComments, $comment['day'], $comment['month'], $this->translate($comment['type'])) ?>
                            <?php endif; ?>
                            <span class="type glyphicons comments"><?= $this->translate($comment['type']); ?> <i></i></span>
                        </div>

                        <div class="widget widget-heading-simple widget-body-white margin-none pagecomment">
                            <div class="widget-body">
                                <div class="media">
                                    <div class="media-object float-left"><img src="<?= $comment['thumbnail']; ?>" alt="Image" width="50" class="rounded-circle"/></div>
                                    <div class="media-body">
                                        <span class="text-danger"><i class="fa fa-user"></i> <?= $this->escapeHtml($name); ?></span><br/>
                                        <span class="muted"><i class="fa fa-envelope"></i> <?= $this->escapeHtml($email); ?></span>
                                        <span class="muted text-small clearfix"><i class="fa fa-clock-o"></i> <?= $comment['time']; ?></span>
                                    </div>
                                </div>
                                <div class="clearfix">
                                    <h4>
                                        <?php
                                        $type = $this->translate($comment['type']);
                                        if ($type == 'WF') {
                                            echo ($comment['cnews_com_title']);
                                        } else {
                                            echo $this->escapeHtml($comment['cnews_com_title']);
                                        }
                                        ?>
                                    </h4>
                                </div>
                                <div class="alert alert-gray">
                                    <?php
                                    $type = $this->translate($comment['type']);
                                    if ($type == 'WF') {
                                        echo $this->escapeHtml($comment['cnews_com_text']);
                                    } else {
                                        echo $comment['cnews_com_text'];
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                    </li>
                    <?php  $isDateDisplayed = false;
                }
                $lastItemMonth = $comment['month'];
                $lastItemDay = $comment['day'];
                ?>

            <?php endif; endforeach; ?>
    </ul>
</div>