<?php
    $id = '';
    if (!empty($this->zoneconfig['conf']['id']))
        $id = $this->zoneconfig['conf']['id'];
    $data_melisKey = $this->melisKey;
?>
<div id="<?= $id; ?>" data-melisKey="<?= $data_melisKey; ?>" class="workflow-modal-cont-news">
    <!-- Modal header-->
    <h4 class="pw-title"> <?= $this->translate('tr_meliscmsnews_workflow_heading'); ?> </h4>
    <?php
        if (!empty($this->zoneconfig['interface'])) {
            foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                echo $this->$keyConfig;
            }
        }
    ?>
</div>
