<!-- Modal content-->
<!-- SET LIMIT TO 6 ENTRY (ADVISABLE) BUT SECTION WILL HAVE SCROLLBARS IF > 6 ENTRIES -->
<div class="workflow-modal-content-news">
	<div class="wmc-content wmc-header clearfix">
		<span> <?= $this->translate('tr_meliscmsnews_tool_col_urole_creation_date'); ?> </span>
		<span> <?= $this->translate('tr_meliscore_tool_user_col_status'); ?> </span>
		<span> <?= $this->translate('tr_meliscmsnews_workflow_user_to'); ?> / <?= $this->translate('tr_meliscmsnews_tool_userrole_Roles'); ?></span>
		<span> <?= $this->translate('tr_meliscmsnews_workflow_user_from'); ?> </span>
		<span> <?= $this->translate('tr_meliscmsnews_tool_col_urole_creation_action'); ?> </span>
	</div>

	<?php

	foreach ($this->workflowItems as $workflowItem) {
		?>
		<div class="wmc-content clearfix">
				<span>
					<span class="r-caption"> <?= $this->translate('tr_meliscmsnews_tool_col_urole_creation_date'); ?> </span>
					<span class="wmc-date"><?= $workflowItem['cnews_wfe_date']; ?></span>
				</span>
				<span>
					<span class="r-caption"> <?php echo $this->translate('tr_meliscore_tool_user_col_status'); ?> </span>
					<?php
						$class = '';
						if ($workflowItem['cnews_wfe_action'] == 'VALIDATION')
							$class = 'asking';
						if ($workflowItem['cnews_wfe_action'] == 'REFUSED')
							$class = 'refused';
						if ($workflowItem['cnews_wfe_action'] == 'VALIDATED')
							$class = 'validated';

						$text = $this->translate('tr_meliscmsnews_workflow_' . $workflowItem['cnews_wfe_action']);
					?>
					<span class="wmc-action-<?= $class; ?>"><?= $text; ?></span>
				</span>
				<span>
					<span class="r-caption"> <?= $this->translate('tr_meliscmsnews_workflow_user_to'); ?> / <?= $this->translate('tr_meliscmsnews_tool_userrole_Roles'); ?></span>
					<?php
						$roleTxt = '';
						if (!empty($workflowItem['cnews_wfe_to_role_name']))
							$roleTxt = ' / ' . $workflowItem['cnews_wfe_to_role_name'];
					?>
					<?= $workflowItem['cnews_wfe_to_user_name']; ?><?= $roleTxt; ?>
				</span>
				<span>
					<span class="r-caption"> <?= $this->translate('tr_meliscmsnews_workflow_user_from'); ?> </span>
					<?= $workflowItem['cnews_wfe_from_user_name']; ?>
				</span>
				<span>
					<span class="r-caption"><?= $this->translate('tr_meliscmsnews_tool_col_urole_creation_action'); ?></span>
					<?php

					if ($workflowItem['cnews_wfe_action'] == 'VALIDATION'
                        && ( (int) $this->currentUserId == (int) $workflowItem['cnews_wfe_to_user_id'])
                        && ( (bool)$workflowItem['isAnswerExisting'] == false)) {

						if (!empty($this->zoneconfig['interface'])) {
							foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
								echo str_replace(array('uniqueid', 'un2'), array($workflowItem['cnews_wfe_id'], $workflowItem['cnews_wfe_wf_id']), $this->$keyConfig);
							}
						}
					} 
					?>
				</span>
		</div>
		<?php
	}
	?>

</div>