<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id .= $this->newsId . '_' . $this->zoneconfig['conf']['id'];
}
?>
<div class="news-preview-tab" id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>">
    <div class="row">
        <div class="col-md-6 col-xs-12 news-preview-title">
            <div class="col-md-12"><h4><?= $this->labels['newsTitlePrefix']; ?> <em>"<?= $this->labels['newsTitle']; ?>"</em></h4></div>
            <div class="col-md-12">
                <?php
                if (!empty($this->newsDetailPageSelector)):
                    echo $this->form()->openTag($this->newsDetailPageSelector);
                    echo $this->melisFieldCollection($this->newsDetailPageSelector);
                    echo $this->form()->closeTag();
                    ?>
                    <script type="text/javascript">
                        (function () {
                            var pageSelector = $body.find("#newsDetailsPageSelectorForm #page-id");
                            if (pageSelector.length > 0) {
                                pageSelector.select2({
                                    width: '100%',
                                    minimumResultsForSearch: -1,
                                    placeholder: translations.tr_meliscmsnews_preview_page_select
                                });
                            }
                        })();
                    </script>
                <?php endif; ?>
            </div>
        </div>
        <div class="col-md-6 col-xs-12 news-preview-btns ">
            <?php if (!empty($this->newsDetailPageSelector)): ?>
            <div class="col-md-12">
                <a class="btn btn-info pull-right" title="<?= $this->labels['seeInTab']; ?>"><?= $this->labels['seeInTab']; ?></a>
            </div>
            <?php endif; ?>
            <div class="col-md-12">
                <a class="btn btn-info pull-right" title="<?= $this->labels['seeInNewTab']; ?>" target="_blank"
                    <?= empty($this->newsURI) ? 'disabled' : ' href="' . $this->newsURI . '"'; ?>>
                    <?= $this->labels['seeInNewTab']; ?>
                </a>
            </div>
        </div>
    </div>

    <div class="row">
        <?php if (!empty($this->newsURI)): ?>
            <div id="<?= $this->newsId; ?>_news-preview-iframe-container" class="col-md-12">
                <div id="loadingZone" class="overlay-loader">
                    <img class="loader-icon spinning-cog" src="/MelisCore/assets/images/cog12.svg" data-cog="cog12">
                </div>
                <iframe class="melis-iframe"
                        src="<?= $this->newsURI; ?>"
                        scrolling="no"
                        data-iframe-id="1"
                        onload="(function() {
                        melisHelper.removeLoadingZone($body.find('#<?= $this->newsId; ?>_news-preview-iframe-container'));
                        // Fixes height issue of the iFrame
                        var height = $body.find('#<?= $this->newsId; ?>_news-preview-iframe-container .melis-iframe').contents().height();
                        $body.find('#<?= $this->newsId; ?>_news-preview-iframe-container .melis-iframe').css('height', height);
                        $body.find('#<?= $this->newsId; ?>_news-preview-iframe-container .melis-iframe').css('min-height', '700px');
                    })();">
                </iframe>
            </div>
        <?php elseif ($this->noPageDetails): ?>
            <div class="col-md-12">
                <div class="alert alert-info" role="alert">
                    <p><?= $this->labels['noPageNewsDetails']; ?></p>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
