<div class="row">
    <div class="col-md-6 col-xs-12">
        <div class="col-md-12"><?= $this->labels['newsTitle']; ?></div>
        <div class="col-md-12">Page selector goes here</div>
    </div>
    <div class="col-md-6 col-xs-12 news-preview-btns ">
        <div class="col-md-12">
            <a class="btn btn-info pull-right" title="<?= $this->labels['seeInTab']; ?>"><?= $this->labels['seeInTab']; ?></a>
        </div>
        <div class="col-md-12">
            <a class="btn btn-info pull-right" title="<?= $this->labels['seeInNewTab']; ?>"><?= $this->labels['seeInNewTab']; ?></a>
        </div>
    </div>
</div>
