<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id .= $this->newsId . '_' . $this->zoneconfig['conf']['id'];
}

?>
<div class="row" id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>">
    <div class="content-cont mcn-width-100">
        <?php
        if (!empty($this->zoneconfig['interface'])) {
            foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                echo $this->$keyConfig;
            }
        }
        ?>
    </div>
</div>
