<?php 
    /**
     * Disabling workflow functionality when news id is not given
     */
    $zoneConfigInterface = $this->zoneconfig['interface'];
    //do not show the workflow button if news id is not given
    if (empty($this->newsId)) {
        unset($zoneConfigInterface['meliscmsnews_content_tabs_properties_header_workflow']);
    }
	if(!empty($zoneConfigInterface)) {
	    foreach($zoneConfigInterface as $keyConfig => $menuConfig) {
	        echo $this->$keyConfig;
	    }
	}
?>