<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id .= $this->newsId.'_'.$this->zoneconfig['conf']['id'];
    }
?>
<div id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>" class="widget widget-tabs widget-tabs-double-2 widget-tabs-responsive">
	<div class="widget-head nav">
		<ul class="tabs-label nav-tabs">
			<?php 
            	if(!empty($this->zoneconfig['interface'])) {
            	    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
            	        
            	        $tabId = $this->newsId.'_'.$menuConfig['conf']['id'];
            	        $tabIcon = $menuConfig['conf']['icon'];
            	        $tabName = $menuConfig['conf']['name'];
            	        
        	            $li= '<li>
                	            <a class="'.$tabIcon.'" data-toggle="tab" href="#'.$tabId.'" aria-expanded="true">
                            		<i></i>
                            		<span>'.$this->translate($tabName).'</span>
                            	</a>
                            </li>';
        	            
        	            if(empty($this->newsId) && ($menuConfig['conf']['melisKey'] == 'meliscmsnews_content_tabs_medias' || $menuConfig['conf']['melisKey'] == 'meliscmsnews_content_tabs_comments')){
        	                $li = '';
        	            }
        	            echo $li;
            	    }
            	}
            ?>
		</ul>
	</div>
</div>
<div class="tab-content innerAll spacing-x2">
	<?php 
    	if(!empty($this->zoneconfig['interface'])) {    	    
    	    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {    	        
	           echo $this->$keyConfig.' ';    	        
    	    }    	    
    	}
    ?>
</div>