<?php
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])) {
        $id .= $this->newsId.'_'.$this->zoneconfig['conf']['id'];
    }

?>

<div class="wizard" id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>">
    <div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
        <div class="widget-body innerAll inner-2x">
            <div class="tab-pane active">
                <div class="row">
                    <div class="col-xs-12 col-md-2">
                        <div class="product-text-tab-container">
                            <ul class="nav-tabs product-text-tab">
                                <?php foreach($this->languages as $idx => $lang) :?>
                                    <li class="">
                                        <a class="clearfix" data-toggle="tab" id="news_cms_lang_<?= $lang['lang_cms_id'] ?>" href="#<?= $lang['lang_cms_name']; ?>-log-type-details-<?= $id; ?>" aria-expanded="true" data-lang-id="<?= $lang['lang_cms_id'] ?>">
                                        <span><?= $lang['lang_cms_name'] ?></span>

                                        <?php 
                                            $img = $lang['lang_cms_locale'];
                                            echo '<span class="pull-right"><img src="/MelisCms/images/lang-flags/'.$img.'.png" class="imgDisplay pull-right"/></span>';
                                        ?>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-10">
                        <div class="tab-content">
                            <?php foreach ($this->languages as $idx => $lang) : ?>
                                <div id="<?= $lang['lang_cms_name']; ?>-log-type-details-<?= $id; ?>" class="tab-pane product-text-tab-content">
                                    <div class="bg-white">
                                        <h4 class=""><i class="fa fa-language" aria-hidden="true"></i> <?= $lang['lang_cms_name']; ?></h4>
                                    </div>
                                    <div id="cnews_<?= $lang['lang_cms_id']; ?>">
                                        <?php
                                            $form = clone $this->formsTitleSubtitle;
                                            if ($this->data) {
                                                foreach ($this->data as $item) {
                                                    if($item['cnews_lang_id'] == $lang['lang_cms_id']){
                                                        $form->setData((array)$item);
                                                    }
                                                } 
                                            }
                                            echo $this->form()->openTag($form);
                                            echo $this->melisFieldCollection($form);
                                            echo $this->form()->closeTag();
                                        ?>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function() {
        let tinyMceOption = {
            height: 300,
            templates: '/melis/MelisCore/MelisTinyMce/getTinyTemplates?siteId=<?= $this->siteId; ?>'
        };
        melisTinyMCE.createTinyMCE("tool", ".editme", tinyMceOption);
    });
</script>
