<?php
$id = '';
$newsId = empty($this->newsId) ? 0 : (int)$this->newsId;
if (!empty($this->zoneconfig['conf']['id'])) {
    $id .= $newsId . '_' . $this->zoneconfig['conf']['id'];
}

$zoneConfigInterface = $this->zoneconfig['interface'];
$tabs = array_keys($zoneConfigInterface);
if (empty($newsId)) {
    /** Disabling "Medias" & "Comments" tabs during creation */
    if (in_array('meliscmsnews_content_tabs_medias', $tabs)) {
        unset($zoneConfigInterface['meliscmsnews_content_tabs_medias']);
    }
    if (in_array('meliscmsnews_content_tabs_comments', $tabs)) {
        unset($zoneConfigInterface['meliscmsnews_content_tabs_comments']);
    }
    if (in_array('meliscmsnews_tabs_preview', $tabs)) {
        unset($zoneConfigInterface['meliscmsnews_tabs_preview']);
    }
    if (in_array('meliscmsnews_workflow_comments', $tabs)) {
        unset($zoneConfigInterface['meliscmsnews_workflow_comments']);
    }
} else {
    /** Post Edition: Remove Comments configuration when MelisCmsComments is disabled */
    if (!in_array('MelisCmsComments', $this->activeModules) && in_array('meliscmsnews_content_tabs_comments', $tabs)) {
        unset($zoneConfigInterface['meliscmsnews_content_tabs_comments']);
    }
    /*do not display the workflow comment tab if Small Business Module is disabled*/
    if ($this->sbIsDisabled) {
        unset($zoneConfigInterface['meliscmsnews_workflow_comments']);
    }
}

?>
<div id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>" class="widget widget-tabs widget-tabs-double-2 widget-tabs-responsive">
    <div class="widget-head nav">
        <ul class="tabs-label nav-tabs nav">
            <?php
            if (!empty($zoneConfigInterface)) {
                foreach ($zoneConfigInterface as $keyConfig => $menuConfig) {
                    $tabId = $newsId . '_' . $menuConfig['conf']['id'];
                    $tabIcon = $menuConfig['conf']['icon'];
                    $tabName = $menuConfig['conf']['name'];

                    $li = '<li class="nav-item">
                            <a class="nav-link ' . $tabIcon . '" data-bs-toggle="tab" data-bs-target="#' . $tabId . '" href="#' . $tabId . '" aria-expanded="true">
                            		<i></i>
                            		<span>' . $this->translate($tabName) . '</span>
                            	</a>
                            </li>';
                    echo $li;
                }
            }
            ?>
        </ul>
    </div>
</div>
<div class="tab-content innerAll spacing-x2">
    <?php
    if (!empty($zoneConfigInterface)) {
        foreach ($zoneConfigInterface as $keyConfig => $menuConfig) {
            echo $this->$keyConfig . ' ';
        }
    }
    ?>
</div>