<?php 
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = $this->zoneconfig['conf']['id'];
    $data_melisKey = $this->melisKey;
?>

<div class="modal-content">
	<div class="modal-body padding-none">
		<div class="wizard">
			<div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                	<ul class="nav nav-tabs">
                		<li class="active"><a href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="glyphicons plus" data-toggle="tab" aria-expanded="true"><i></i><?= $this->zoneconfig['conf']['name']?> 
                		</a>
                		
                		</li>                		
            		</ul>
        		</div>
        		<div class="widget-body innerAll inner-2x">
        			<div class="tab-content">
        				<div class="tab-pane active" id="<?= $id ?>">
                            <div class="row">
                            	<div class="col-md-12" id="newsAttachement">
                                		<?php 
                                		$img = empty($this->file)? $this->default : $this->file;
                                		if($this->type == 'image'):?>
                                		<div class="center-block">
                                            <span class="thumbnail">
                                              <img class="imgDocThumbnail" width="128" height="128" src="<?= $img?>">
                                            </span>
                                        </div>
                                          <?php 
                                          
                                          endif;
                                          
                                          echo $this->form()->openTag($this->form);
                                          echo $this->melisFieldCollection($this->form);
                                          echo $this->form()->closeTag();
                                          ?>
                                          	<script type="text/javascript">
                                            	$(":file").filestyle({buttonBefore: true, input: true, buttonText: '&nbsp;<?php echo $this->translate('tr_meliscmsnews_input_file')?>', placeholder : '<?= str_replace("'", "\'" ,$this->file)?>'});
                                            </script>
                                            <div class="progressContent hidden">
                                                <?= $this->translate('tr_meliscmsnews_input_file_uploading'); ?>
                                                <div class="progress">
                                                	<span class="status float-right text-danger hidden">0%</span>
                                                  <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" aria-valuenow=0 aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                                                  </div>
                                                </div><br/>
                        					</div>  
                                         <br> 	                
                                    <div class="footer-modal d-flex flex-row justify-content-between">
                                 		<button data-dismiss="modal" class="btn btn-danger float-left"><i class="fa fa-times"></i> <?php echo $this->translate('tr_meliscmsnews_form_btn_cancel')?></button>
                                 		<button class="btn btn-success" id="newsAttachment"><i class="fa fa-save"></i>  <?php echo $this->translate('tr_meliscmsnews_header_right_save') ?></button>
                                 	</div>                                 	
                            	</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>