<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id .= $this->newsId . '_' . $this->zoneconfig['conf']['id'] . '_' . $this->entityType;;
}
?>
<div id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>">
    <div class="npdc-heading pt-4">
        <h4>
            <i class="fa fa-tag"></i>
            <?= $this->translate('tr_melis_cms_tags_list_header_title') ?>
        </h4>
    </div>
    <div class="pdc-content border-bottom">
        <?php

        echo $this->form()->openTag($this->form);
        echo $this->melisFieldCollection($this->form);
        echo $this->form()->closeTag();

        ?>
        <br>
    </div>
</div>
<script>
    $(document).ready(function () {
        var tagSelector = $body.find("#<?php echo $id; ?> #tags_select");
        if (tagSelector.length > 0) {
            tagSelector.select2({
                ajax: {
                    type: 'POST',
                    url: "/melis/MelisCmsTags/Tag/getSelectTags",
                    dataType: 'json',
                    delay: 500,
                    minimumInputLength: -1,
                    data: function (params) {
                        return {
                            'searchValue': params.term, // search term
                            // 'tagType': <?php // echo $this->entityTypeId; ?>,
                        };
                    },
                    cache: true
                },
                width: '100%',
                disabled: false,
                language: {
                    noResults: function () {
                        return translations.tr_melis_cms_user_selection_empty;
                    },
                    searching: function () {
                        return translations.tr_melis_cms_user_searching;
                    }
                },
                allowClear: true,
                placeholder: translations.tr_meliscms_form_common_Choose
            }).// These following events were added to prevent select2 from opening when clearing
            on('select2:unselecting', function () {
                $(this).data('unselecting', true);
            }).on('select2:opening', function (e) {
                if ($(this).data('unselecting')) {
                    $(this).removeData('unselecting');
                    e.preventDefault();
                }
            });

            <?php if($this->tags) : ?>

                <?php foreach ($this->tags as $tag) : ?>
                    var newOption = new Option("<?php echo $tag['text']; ?>",<?php echo $tag['id']; ?>, true, true);
                    tagSelector.append(newOption).trigger('change');
                <?php endforeach; ?>
            <?php endif; ?>

        }
    });
</script>