<div class="col-xs-12 height-fix">
	<?php
	$id = '';
	if (!empty($this->zoneconfig['conf']['id'])){
	    $id .= $this->newsId.'_'.$this->zoneconfig['conf']['id'];
	}
	$collapse = 'collapse in';
    $collapsed = '';
	?>
	<div id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>">
		<div class="npdc-heading">
    		<h4>
    			<i class="fa fa-align-left"></i>
    			<?= $this->translate('tr_meliscmsnews_subheader_paragraphs')?>
    		</h4>
		</div>
		<?php 
		$c = 1;
		foreach($this->forms as $form):
		?>
		<a class="btn btn-primary form-control a-accordion <?= $collapsed?>" data-toggle="collapse" href="#<?= $this->newsId ?>_paragraph<?= $c?>" aria-expanded="false" aria-controls="payment1">
    		<span><?= $this->translate('tr_meliscmsnews_common_paragraph').' '.$c?></span>
    	</a>
    	<div class="<?= $collapse?>" id="<?= $this->newsId ?>_paragraph<?= $c?>">
    	<?php 
    	echo $this->form()->openTag($form);
    	echo $this->melisFieldCollection($form);
    	echo $this->form()->closeTag();
    	?>
    	<script type="text/javascript">
    	
    	if (typeof tinymce != "undefined") {
        	var id = "<?= $this->newsId?>_cnews_paragraph<?= $c?>";
    	    var ed = tinymce.get(id);
    	    if (ed) {
    	        try {
    	            ed.remove();
    	        } catch(e) {
    	            delete tinymce.editors[id];
    	        }
    	    }
    	}
    	melisTinyMCE.createTinyMCE("tool", "#<?= $this->newsId?>_cnews_paragraph<?= $c?>", {height: 300});
    	   	
    	</script>
    	</div>
		<?php 
		$collapsed = 'collapsed';
		$collapse = 'collapse';
		$c++;
		endforeach;
		?>    	
    	
    	
	</div>
</div>