<div>
	<div class="npdc-heading">
		<h4>
			<i class="fa fa-tags"></i>
			<?= $this->translate('tr_meliscmsnews_subheader_title');?>
		</h4>						
		
	</div>						
	<div class="pdc-content border-bottom">
		 <?php 
		 echo $this->form()->openTag($this->form);
		 echo $this->melisFieldCollection($this->form);
		 echo $this->form()->closeTag();
		 ?>
		 <br>
	</div>
	<?php 
	   echo $this->datePickerInit;
	?>
</div>