<div class="col-xs-12 col-lg-6">
    <?php
    $layout = $this->zoneconfig['interface'];
    if (!empty($layout)) {
        /**
         * Removing "Validate Comments" field from the interface when MelisCmsComments DISABLED
         */
        if ($this->commentsModuleIsDisabled === true) {
            unset($layout['meliscms_comments_validate_comments_news']);
        }

        foreach ($layout as $keyConfig => $menuConfig) {
            echo $this->$keyConfig;
        }
    }
    ?>
</div>